---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: hw
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./workloads/hw
  prune: true
  sourceRef:
    kind: GitRepository
    name: bookinfo
  validation: client

